[package]
name = "interlinked"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
]

[workspace.dependencies]
soroban-sdk = "22"

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
log = "0.4.25"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }